### ISSUE TITLE
Some questions about calculation of biosynthetic diversity (Shannon index based on natural product types)

### ISSUE THREAD

**Issue by ZongzhiWu** [SushiLab/magpipe#1]
Dear Lucas, 

I read your paper 'Biosynthetic potential of the global ocean microbiome'. I noted that you calculated the biosynthetic diversity (Shannon index based on natural product types) of each BGC-enriched specie. However, the description of biosynthetic diversity calculation in your method is succinct. Could you please take an example of calculation of biosynthetic diversity of ‘Ca. Eudoremicrobiaceae’ spp?

Best wishes!

**Comment by LucasPaoli** [comment]
Thank you very much for your interest in this work.

The exact script used is available [here](https://github.com/SushiLab/magpipe/blob/master/figures/Figure-2D-biosynth_diversity.R) and the results are in [Suppl. table 3](https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-022-04862-3/MediaObjects/41586_2022_4862_MOESM6_ESM.xlsx).

If we take the example of [Ca. Eudoremicrobium malaspinii](https://sunagawalab.ethz.ch/share/microbiomics/ocean/db/1.0/marine_eremios/annotations/MALA_SAMN05422137_METAG_HLLJDLBE/antismash/MALA_SAMN05422137_METAG_HLLJDLBE-antismash/), it has (make sure that hybrids have products listed in alphabetical order to prevent duplicates):

```
                        arylpolyene                         bacteriocin 
                                  1                                   2 
bacteriocin;lanthipeptide;proteusin               bacteriocin;proteusin 
                                  1                                   2 
                            ectoine               hglE-KS;T1PKS;terpene 
                                  1                                   1 
                       microviridin                           NRPS-like 
                                  2                                   3 
                        phosphonate                         siderophore 
                                  1                                   1 
                              T1PKS                     T1PKS;NRPS-like 
                                  1                                   1 
                              T3PKS                             terpene 
                                  1                                   3 
```

We can then calculate the Shannon diversity of this biosynthetic potential, which gives us 2.53 (see table S3, sheet 'BGC-rich lineages')

I hope this helps and I will close the comment for now, but do let me know if you have other questions.

**Comment by ZongzhiWu** [comment]
Thanks a lot! :)
