### ISSUE TITLE
Some questions about "Clustering and selection of BGCs " of the article

### ISSUE THREAD

**Issue by yiyanli123** [SushiLab/magpipe#2]
Dear Lucas,
    Thanks for your work! I am currently examining the **Clustering and selection of BGCs** section within the 'Methods' portion of your article titled 'Biosynthetic potential of the global ocean microbiome.' 
    I would like to inquire about the tools employed for “computing all-versus-all cosine distances between BGCs and clustered them (average linkage) into GCFs and GCCs”, Were Python libraries or R libraries utilized for this purpose?

Best regards!

**Comment by guoqing-zhang** [comment]
您好，我是张国庆，您的邮件已收到。我会尽快回复您！

**Comment by LucasPaoli** [comment]
Thank you for your interest and apologies for the delayed answer.

For this analysis we used the BiG-SLICE software. The paper for this tool is available [there](https://doi.org/10.1093/gigascience/giaa154) and the GitHub repo [here](https://github.com/medema-group/bigslice). However, we replaced the default Euclidean distances computed by BiG-SLICE and used cosine distances instead. This can easily be done in python by loading the bgc_features table from BiG-SLICE database (data.db after a default BiG-SLICE run) and computing the cosine distances and the downstream clustering in python using the sklearn package. Using the cosine distance, the clustering threshold can then be updated to 0.2 and 0.8 for GCFs and GCCs, respectively. 

Once you have loaded the bgc_features as a pandas dataframe, this could be implemented as follows:

```
import pickle
from sklearn.metrics import pairwise_distances
from sklearn.cluster import AgglomerativeClustering

print("calculating pairwise distances...")
pairwise_dists = pairwise_distances(bgc_features.values, metric="cosine", n_jobs=1)

print("perform clusterings...")
def call_clustering(dist_matrix, threshold):
    return AgglomerativeClustering(
        distance_threshold=threshold,
        n_clusters=None,
        affinity="precomputed",
        linkage="average"
    ).fit(dist_matrix)

for threshold in [0.2, 0.8]:
    with open(f"clustering_{threshold}.pkl", "wb") as pkl_file:
        print(f"clustering t={threshold}...")
        pickle.dump(call_clustering(pairwise_dists, threshold), pkl_file)
```

For alternative clustering strategies, you can also have a look at [this paper](https://doi.org/10.1038/s41564-022-01110-2).

I will close the issue for now, but don’t hesitate if you have any follow up questions.

Best wishes,

Lucas

**Comment by guoqing-zhang** [comment]
您好，我是张国庆，您的邮件已收到。我会尽快回复您！
